const DungeonList = Object.freeze({
    [Dungeons.TinyWoods]: {
        "name": "Tiny Woods",
        "stairDirectionUp": false,
        "recruitingEnabled": false,
        "maxItemsAllowed": 20,
        "maxPartyMembers": 3,
        "keepMoney": true,
    },
    [Dungeons.ThunderwaveCave]: {
        "name": "Thunderwave Cave",
        "stairDirectionUp": false,
        "recruitingEnabled": true,
        "maxItemsAllowed": 20,
        "maxPartyMembers": 3,
        "keepMoney": true,
    },
    [Dungeons.MtSteel]: {
        "name": "Mt. Steel",
        "stairDirectionUp": true,
        "recruitingEnabled": true,
        "maxItemsAllowed": 20,
        "maxPartyMembers": 3,
        "keepMoney": true,
    },
    [Dungeons.SinisterWoods]: {
        "name": "Sinister Woods",
        "stairDirectionUp": true,
        "recruitingEnabled": true,
        "maxItemsAllowed": 20,
        "maxPartyMembers": 3,
        "keepMoney": true,
    },
    [Dungeons.SilentChasm]: {
        "name": "Silent Chasm",
        "stairDirectionUp": false,
        "recruitingEnabled": true,
        "maxItemsAllowed": 20,
        "maxPartyMembers": 3,
        "keepMoney": true,
    },
    [Dungeons.MtThunder]: {
        "name": "Mt. Thunder",
        "stairDirectionUp": true,
        "recruitingEnabled": true,
        "maxItemsAllowed": 20,
        "maxPartyMembers": 3,
        "keepMoney": true,
        "hasCheckpoint": true,
    },
    [Dungeons.MtThunderPeak]: {
        "name": "Mt. Thunder Peak",
        "stairDirectionUp": true,
        "recruitingEnabled": true,
        "maxItemsAllowed": 20,
        "maxPartyMembers": 4,
        "keepMoney": true,
    },
    [Dungeons.GreatCanyon]: {
        "name": "Great Canyon",
        "stairDirectionUp": true,
        "recruitingEnabled": true,
        "maxItemsAllowed": 20,
        "maxPartyMembers": 3,
        "keepMoney": true,
    },
    [Dungeons.LapisCave]: {
        "name": "Lapis Cave",
        "stairDirectionUp": false,
        "recruitingEnabled": true,
        "maxItemsAllowed": 20,
        "maxPartyMembers": 3,
        "keepMoney": true,
    },
    [Dungeons.MtBlaze]: {
        "name": "Mt. Blaze",
        "stairDirectionUp": true,
        "recruitingEnabled": true,
        "maxItemsAllowed": 20,
        "maxPartyMembers": 3,
        "keepMoney": true,
        "hasCheckpoint": true,
    },
    [Dungeons.MtBlazePeak]: {
        "name": "Mt. Blaze Peak",
        "stairDirectionUp": true,
        "recruitingEnabled": true,
        "maxItemsAllowed": 20,
        "maxPartyMembers": 4,
        "keepMoney": true,
    },
    [Dungeons.FrostyForest]: {
        "name": "Frosty Forest",
        "stairDirectionUp": true,
        "recruitingEnabled": true,
        "maxItemsAllowed": 20,
        "maxPartyMembers": 3,
        "keepMoney": true,
        "hasCheckpoint": true,
    },
    [Dungeons.FrostyGrotto]: {
        "name": "Frosty Grotto",
        "stairDirectionUp": true,
        "recruitingEnabled": true,
        "maxItemsAllowed": 20,
        "maxPartyMembers": 4,
        "keepMoney": true,
    },
    [Dungeons.MtFreeze]: {
        "name": "Mt. Freeze",
        "stairDirectionUp": true,
        "recruitingEnabled": true,
        "maxItemsAllowed": 20,
        "maxPartyMembers": 3,
        "keepMoney": true,
        "hasCheckpoint": true,
    },
    [Dungeons.MtFreezePeak]: {
        "name": "Mt. Freeze Peak",
        "stairDirectionUp": true,
        "recruitingEnabled": true,
        "maxItemsAllowed": 20,
        "maxPartyMembers": 4,
        "keepMoney": true,
    },
    [Dungeons.MagmaCavern]: {
        "name": "Magma Cavern",
        "stairDirectionUp": false,
        "recruitingEnabled": true,
        "maxItemsAllowed": 20,
        "maxPartyMembers": 3,
        "keepMoney": true,
        "hasCheckpoint": true,
    },
    [Dungeons.MagmaCavernPit]: {
        "name": "Magma Cavern Pit",
        "stairDirectionUp": false,
        "recruitingEnabled": true,
        "maxItemsAllowed": 20,
        "maxPartyMembers": 4,
        "keepMoney": true,
    },
    [Dungeons.SkyTower]: {
        "name": "Sky Tower",
        "stairDirectionUp": true,
        "recruitingEnabled": true,
        "maxItemsAllowed": 20,
        "maxPartyMembers": 3,
        "keepMoney": true,
        "hasCheckpoint": true,
    },
    [Dungeons.SkyTowerSummit]: {
        "name": "Sky Tower Summit",
        "stairDirectionUp": true,
        "recruitingEnabled": true,
        "maxItemsAllowed": 20,
        "maxPartyMembers": 4,
        "keepMoney": true,
    },
    [Dungeons.StormySea]: {
        "name": "Stormy Sea",
        "stairDirectionUp": false,
        "recruitingEnabled": true,
        "maxItemsAllowed": 20,
        "maxPartyMembers": 3,
        "keepMoney": true,
        "leaderCanSwitch": true,
    },
    [Dungeons.SilverTrench]: {
        "name": "Silver Trench",
        "stairDirectionUp": false,
        "recruitingEnabled": true,
        "maxItemsAllowed": 20,
        "maxPartyMembers": 3,
        "keepMoney": true,
        "leaderCanSwitch": true,
    },
    [Dungeons.MeteorCave]: {
        "name": "Meteor Cave",
        "stairDirectionUp": false,
        "recruitingEnabled": true,
        "maxItemsAllowed": 3,
        "maxPartyMembers": 1,
        "keepMoney": true,
    },
    // [Dungeons.MtFreezePeak2]: {
    //     "name": "Mt. Freeze Peak 2",
    //     "stairDirectionUp": true,
    //     "recruitingEnabled": false,
    //     "maxItemsAllowed": 20,
    //     "maxPartyMembers": 4,
    //     "keepMoney": true,
    // },
    [Dungeons.WesternCave]: {
        "name": "Western Cave",
        "stairDirectionUp": false,
        "recruitingEnabled": true,
        "maxItemsAllowed": 20,
        "maxPartyMembers": 3,
        "keepMoney": true,
        "leaderCanSwitch": true,
    },
    // [Dungeons.Boss3]: {
    //     "name": "Boss 3",
    //     "stairDirectionUp": false,
    //     "recruitingEnabled": false,
    //     "maxItemsAllowed": 20,
    //     "maxPartyMembers": 3,
    //     "keepMoney": true,
    // },
    // [Dungeons.Boss4]: {
    //     "name": "Boss 4",
    //     "stairDirectionUp": false,
    //     "recruitingEnabled": false,
    //     "maxItemsAllowed": 20,
    //     "maxPartyMembers": 3,
    //     "keepMoney": true,
    // },
    [Dungeons.WishCave]: {
        "name": "Wish Cave",
        "stairDirectionUp": false,
        "recruitingEnabled": true,
        "maxItemsAllowed": 20,
        "maxPartyMembers": 3,
        "levelResetTo1": true,
        "keepMoney": false,
        "leaderCanSwitch": true,
    },
    [Dungeons.BuriedRelic]: {
        "name": "Buried Relic",
        "stairDirectionUp": false,
        "recruitingEnabled": true,
        "maxItemsAllowed": 20,
        "maxPartyMembers": 3,
        "keepMoney": true,
        "leaderCanSwitch": true,
    },
    [Dungeons.PitfallValley]: {
        "name": "Pitfall Valley",
        "stairDirectionUp": false,
        "recruitingEnabled": true,
        "maxItemsAllowed": 20,
        "maxPartyMembers": 3,
        "keepMoney": true,
        "leaderCanSwitch": true,
    },
    [Dungeons.NorthernRange]: {
        "name": "Northern Range",
        "stairDirectionUp": true,
        "recruitingEnabled": true,
        "maxItemsAllowed": 20,
        "maxPartyMembers": 3,
        "keepMoney": true,
        "leaderCanSwitch": true,
    },
    // [Dungeons.Boss9]: {
    //     "name": "Boss 9",
    //     "stairDirectionUp": false,
    //     "recruitingEnabled": false,
    //     "maxItemsAllowed": 20,
    //     "maxPartyMembers": 3,
    //     "keepMoney": true,
    // },
    [Dungeons.DesertRegion]: {
        "name": "Desert Region",
        "stairDirectionUp": true,
        "recruitingEnabled": true,
        "maxItemsAllowed": 20,
        "maxPartyMembers": 3,
        "keepMoney": true,
        "leaderCanSwitch": true,
    },
    [Dungeons.SouthernCavern]: {
        "name": "Southern Cavern",
        "stairDirectionUp": false,
        "recruitingEnabled": true,
        "maxItemsAllowed": 20,
        "maxPartyMembers": 3,
        "keepMoney": true,
        "leaderCanSwitch": true,
    },
    [Dungeons.WyvernHill]: {
        "name": "Wyvern Hill",
        "stairDirectionUp": true,
        "recruitingEnabled": true,
        "maxItemsAllowed": 20,
        "maxPartyMembers": 3,
        "keepMoney": true,
        "leaderCanSwitch": true,
    },
    [Dungeons.FieryField]: {
        "name": "Fiery Field",
        "stairDirectionUp": true,
        "recruitingEnabled": true,
        "maxItemsAllowed": 20,
        "maxPartyMembers": 3,
        "keepMoney": true,
        "leaderCanSwitch": true,
    },
    [Dungeons.NorthwindField]: {
        "name": "Northwind Field",
        "stairDirectionUp": true,
        "recruitingEnabled": true,
        "maxItemsAllowed": 20,
        "maxPartyMembers": 3,
        "keepMoney": true,
        "leaderCanSwitch": true,
    },
    [Dungeons.SolarCave]: {
        "name": "Solar Cave",
        "stairDirectionUp": false,
        "recruitingEnabled": true,
        "maxItemsAllowed": 20,
        "maxPartyMembers": 3,
        "keepMoney": true,
        "leaderCanSwitch": true,
    },
    [Dungeons.LightningField]: {
        "name": "Lightning Field",
        "stairDirectionUp": true,
        "recruitingEnabled": true,
        "maxItemsAllowed": 20,
        "maxPartyMembers": 3,
        "keepMoney": true,
        "leaderCanSwitch": true,
    },
    [Dungeons.DarknightRelic]: {
        "name": "Darknight Relic",
        "stairDirectionUp": false,
        "recruitingEnabled": true,
        "maxItemsAllowed": 20,
        "maxPartyMembers": 3,
        "keepMoney": true,
        "leaderCanSwitch": true,
    },
    // [Dungeons.WondrousSea]: {
    //     "name": "Wondrous Sea",
    //     "stairDirectionUp": false,
    //     "recruitingEnabled": true,
    //     "maxItemsAllowed": 20,
    //     "maxPartyMembers": 3,
    //     "keepMoney": true,
    // },
    [Dungeons.MurkyCave]: {
        "name": "Murky Cave",
        "stairDirectionUp": false,
        "recruitingEnabled": true,
        "maxItemsAllowed": 20,
        "maxPartyMembers": 3,
        "keepMoney": true,
    },
    [Dungeons.GrandSea]: {
        "name": "Grand Sea",
        "stairDirectionUp": false,
        "recruitingEnabled": true,
        "maxItemsAllowed": 20,
        "maxPartyMembers": 3,
        "keepMoney": true,
        "leaderCanSwitch": true,
    },
    [Dungeons.UproarForest]: {
        "name": "Uproar Forest",
        "stairDirectionUp": false,
        "recruitingEnabled": true,
        "maxItemsAllowed": 20,
        "maxPartyMembers": 3,
        "keepMoney": true,
    },
    [Dungeons.OddityCave]: {
        "name": "Oddity Cave",
        "stairDirectionUp": false,
        "recruitingEnabled": true,
        "maxItemsAllowed": 20,
        "maxPartyMembers": 3,
        "keepMoney": true,
    },
    [Dungeons.RemainsIsland]: {
        "name": "Remains Island",
        "stairDirectionUp": false,
        "recruitingEnabled": true,
        "maxItemsAllowed": 20,
        "maxPartyMembers": 3,
        "keepMoney": true,
    },
    [Dungeons.MarvelousSea]: {
        "name": "Marvelous Sea",
        "stairDirectionUp": false,
        "recruitingEnabled": true,
        "maxItemsAllowed": 20,
        "maxPartyMembers": 3,
        "keepMoney": true,
    },
    [Dungeons.FantasyStrait]: {
        "name": "Fantasy Strait",
        "stairDirectionUp": false,
        "recruitingEnabled": true,
        "maxItemsAllowed": 20,
        "maxPartyMembers": 3,
        "keepMoney": true,
    },
    [Dungeons.RockPath]: {
        "name": "Rock Path",
        "stairDirectionUp": false,
        "recruitingEnabled": false,
        "maxItemsAllowed": 20,
        "maxPartyMembers": 3,
        "keepMoney": true,
    },
    [Dungeons.SnowPath]: {
        "name": "Snow Path",
        "stairDirectionUp": false,
        "recruitingEnabled": false,
        "maxItemsAllowed": 20,
        "maxPartyMembers": 3,
        "keepMoney": true,
    },
    // [Dungeons.Autopilot]: {
    //     "name": "Autopilot",
    //     "stairDirectionUp": false,
    //     "recruitingEnabled": false,
    //     "maxItemsAllowed": 20,
    //     "maxPartyMembers": 3,
    //     "keepMoney": true,
    // },
    // [Dungeons.D50]: {
    //     "name": "D50",
    //     "stairDirectionUp": false,
    //     "recruitingEnabled": false,
    //     "maxItemsAllowed": 20,
    //     "maxPartyMembers": 3,
    //     "keepMoney": true,
    // },
    // [Dungeons.D51]: {
    //     "name": "D51",
    //     "stairDirectionUp": false,
    //     "recruitingEnabled": false,
    //     "maxItemsAllowed": 20,
    //     "maxPartyMembers": 3,
    //     "keepMoney": true,
    // },
    // [Dungeons.NormalMaze]: {
    //     "name": "Normal Maze",
    //     "stairDirectionUp": false,
    //     "recruitingEnabled": false,
    //     "maxItemsAllowed": 20,
    //     "maxPartyMembers": 3,
    //     "keepMoney": true,
    // },
    [Dungeons.HowlingForest]: {
        "name": "Howling Forest",
        "stairDirectionUp": true,
        "recruitingEnabled": true,
        "maxItemsAllowed": 20,
        "maxPartyMembers": 3,
        "keepMoney": true,
    },
    // [Dungeons.D54]: {
    //     "name": "D54",
    //     "stairDirectionUp": false,
    //     "recruitingEnabled": false,
    //     "maxItemsAllowed": 20,
    //     "maxPartyMembers": 3,
    //     "keepMoney": true,
    // },
    // [Dungeons.PoisonMaze]: {
    //     "name": "Poison Maze",
    //     "stairDirectionUp": false,
    //     "recruitingEnabled": false,
    //     "maxItemsAllowed": 20,
    //     "maxPartyMembers": 3,
    //     "keepMoney": true,
    // },
    [Dungeons.WaterfallPond]: {
        "name": "Waterfall Pond",
        "stairDirectionUp": false,
        "recruitingEnabled": true,
        "maxItemsAllowed": 20,
        "maxPartyMembers": 3,
        "keepMoney": true,
    },
    [Dungeons.UnownRelic]: {
        "name": "Unown Relic",
        "stairDirectionUp": false,
        "recruitingEnabled": true,
        "maxItemsAllowed": 20,
        "maxPartyMembers": 3,
        "keepMoney": true,
    },
    [Dungeons.JoyousTower]: {
        "name": "Joyous Tower",
        "stairDirectionUp": true,
        "recruitingEnabled": true,
        "maxItemsAllowed": 20,
        "maxPartyMembers": 3,
        "levelResetTo1": true,
        "keepMoney": false,
        "leaderCanSwitch": true,
    },
    [Dungeons.FarOffSea]: {
        "name": "Far-Off Sea",
        "stairDirectionUp": false,
        "recruitingEnabled": true,
        "maxItemsAllowed": 20,
        "maxPartyMembers": 3,
        "keepMoney": true,
    },
    [Dungeons.MtFaraway]: {
        "name": "Mt. Faraway",
        "stairDirectionUp": true,
        "recruitingEnabled": true,
        "maxItemsAllowed": 20,
        "maxPartyMembers": 3,
        "keepMoney": true,
        "leaderCanSwitch": true,
    },
    // [Dungeons.D61]: {
    //     "name": "D61",
    //     "stairDirectionUp": false,
    //     "recruitingEnabled": false,
    //     "maxItemsAllowed": 10,
    //     "maxPartyMembers": 3,
    //     "keepMoney": true,
    // },
    [Dungeons.PurityForest]: {
        "name": "Purity Forest",
        "stairDirectionUp": true,
        "recruitingEnabled": false,
        "maxItemsAllowed": 0,
        "maxPartyMembers": 1,
        "levelResetTo1": true,
        "keepMoney": false,
    },
    // [Dungeons.OutOnRescue]: {
    //     "name": "Out On Rescue",
    //     "stairDirectionUp": false,
    //     "recruitingEnabled": true,
    //     "maxItemsAllowed": 20,
    //     "maxPartyMembers": 3,
    //     "keepMoney": true,
    // },
    // [Dungeons.JoinLocationLeader]: {
    //     "name": "Join Location Leader",
    //     "stairDirectionUp": false,
    //     "recruitingEnabled": true,
    //     "maxItemsAllowed": 20,
    //     "maxPartyMembers": 3,
    //     "keepMoney": true,
    // },
    // [Dungeons.JoinLocationPartner]: {
    //     "name": "Join Location Partner",
    //     "stairDirectionUp": false,
    //     "recruitingEnabled": true,
    //     "maxItemsAllowed": 20,
    //     "maxPartyMembers": 3,
    //     "keepMoney": true,
    // },
    // [Dungeons.UnknownWorld]: {
    //     "name": "Unknown World",
    //     "stairDirectionUp": false,
    //     "recruitingEnabled": true,
    //     "maxItemsAllowed": 20,
    //     "maxPartyMembers": 3,
    //     "keepMoney": true,
    // },
    // [Dungeons.FrostyGrotto2]: {
    //     "name": "Frosty Grotto 2",
    //     "stairDirectionUp": false,
    //     "recruitingEnabled": true,
    //     "maxItemsAllowed": 20,
    //     "maxPartyMembers": 3,
    //     "keepMoney": true,
    // },
    // [Dungeons.HowlingForest2]: {
    //     "name": "Howling Forest 2",
    //     "stairDirectionUp": false,
    //     "recruitingEnabled": true,
    //     "maxItemsAllowed": 20,
    //     "maxPartyMembers": 3,
    //     "keepMoney": true,
    // },
    // [Dungeons.PokemonSquare]: {
    //     "name": "Pokemon Square",
    //     "stairDirectionUp": false,
    //     "recruitingEnabled": true,
    //     "maxItemsAllowed": 20,
    //     "maxPartyMembers": 3,
    //     "keepMoney": true,
    // },
    // [Dungeons.PokemonSquare2]: {
    //     "name": "Pokemon Square 2",
    //     "stairDirectionUp": false,
    //     "recruitingEnabled": true,
    //     "maxItemsAllowed": 20,
    //     "maxPartyMembers": 3,
    //     "keepMoney": true,
    // },
    // [Dungeons.RescueTeamBase]: {
    //     "name": "Rescue Team Base",
    //     "stairDirectionUp": false,
    //     "recruitingEnabled": true,
    //     "maxItemsAllowed": 20,
    //     "maxPartyMembers": 3,
    //     "keepMoney": true,
    // },
    // [Dungeons.RescueTeamBase2]: {
    //     "name": "Rescue Team Base 2",
    //     "stairDirectionUp": false,
    //     "recruitingEnabled": true,
    //     "maxItemsAllowed": 20,
    //     "maxPartyMembers": 3,
    //     "keepMoney": true,
    // },
    // [Dungeons.AgbSlot]: {
    //     "name": "Agb Slot",
    //     "stairDirectionUp": false,
    //     "recruitingEnabled": true,
    //     "maxItemsAllowed": 20,
    //     "maxPartyMembers": 3,
    //     "keepMoney": true,
    // },
    // [Dungeons.JoinLocationClientPokemon]: {
    //     "name": "Join Location Client Pokemon",
    //     "stairDirectionUp": false,
    //     "recruitingEnabled": true,
    //     "maxItemsAllowed": 20,
    //     "maxPartyMembers": 3,
    //     "keepMoney": true,
    // },
    // [Dungeons.NormalMaze2]: {
    //     "name": "Normal Maze 2",
    //     "stairDirectionUp": false,
    //     "recruitingEnabled": false,
    //     "maxItemsAllowed": 20,
    //     "maxPartyMembers": 3,
    //     "keepMoney": true,
    // },
    // [Dungeons.FireMaze]: {
    //     "name": "Fire Maze",
    //     "stairDirectionUp": false,
    //     "recruitingEnabled": false,
    //     "maxItemsAllowed": 20,
    //     "maxPartyMembers": 3,
    //     "keepMoney": true,
    // },
    // [Dungeons.WaterMaze]: {
    //     "name": "Water Maze",
    //     "stairDirectionUp": false,
    //     "recruitingEnabled": false,
    //     "maxItemsAllowed": 20,
    //     "maxPartyMembers": 3,
    //     "keepMoney": true,
    // },
    // [Dungeons.GrassMaze]: {
    //     "name": "Grass Maze",
    //     "stairDirectionUp": false,
    //     "recruitingEnabled": false,
    //     "maxItemsAllowed": 20,
    //     "maxPartyMembers": 3,
    //     "keepMoney": true,
    // },
    // [Dungeons.ElectricMaze]: {
    //     "name": "Electric Maze",
    //     "stairDirectionUp": false,
    //     "recruitingEnabled": false,
    //     "maxItemsAllowed": 20,
    //     "maxPartyMembers": 3,
    //     "keepMoney": true,
    // },
    // [Dungeons.IceMaze]: {
    //     "name": "Ice Maze",
    //     "stairDirectionUp": false,
    //     "recruitingEnabled": false,
    //     "maxItemsAllowed": 20,
    //     "maxPartyMembers": 3,
    //     "keepMoney": true,
    // },
    // [Dungeons.FightingMaze]: {
    //     "name": "Fighting Maze",
    //     "stairDirectionUp": false,
    //     "recruitingEnabled": false,
    //     "maxItemsAllowed": 20,
    //     "maxPartyMembers": 3,
    //     "keepMoney": true,
    // },
    // [Dungeons.GroundMaze]: {
    //     "name": "Ground Maze",
    //     "stairDirectionUp": false,
    //     "recruitingEnabled": false,
    //     "maxItemsAllowed": 20,
    //     "maxPartyMembers": 3,
    //     "keepMoney": true,
    // },
    // [Dungeons.FlyingMaze]: {
    //     "name": "Flying Maze",
    //     "stairDirectionUp": false,
    //     "recruitingEnabled": false,
    //     "maxItemsAllowed": 20,
    //     "maxPartyMembers": 3,
    //     "keepMoney": true,
    // },
    // [Dungeons.PsychicMaze]: {
    //     "name": "Psychic Maze",
    //     "stairDirectionUp": false,
    //     "recruitingEnabled": false,
    //     "maxItemsAllowed": 20,
    //     "maxPartyMembers": 3,
    //     "keepMoney": true,
    // },
    // [Dungeons.PoisonMaze2]: {
    //     "name": "Poison Maze 2",
    //     "stairDirectionUp": false,
    //     "recruitingEnabled": false,
    //     "maxItemsAllowed": 20,
    //     "maxPartyMembers": 3,
    //     "keepMoney": true,
    // },
    // [Dungeons.BugMaze]: {
    //     "name": "Bug Maze",
    //     "stairDirectionUp": false,
    //     "recruitingEnabled": false,
    //     "maxItemsAllowed": 20,
    //     "maxPartyMembers": 3,
    //     "keepMoney": true,
    // },
    // [Dungeons.RockMaze]: {
    //     "name": "Rock Maze",
    //     "stairDirectionUp": false,
    //     "recruitingEnabled": false,
    //     "maxItemsAllowed": 20,
    //     "maxPartyMembers": 3,
    //     "keepMoney": true,
    // },
    // [Dungeons.GhostMaze]: {
    //     "name": "Ghost Maze",
    //     "stairDirectionUp": false,
    //     "recruitingEnabled": false,
    //     "maxItemsAllowed": 20,
    //     "maxPartyMembers": 3,
    //     "keepMoney": true,
    // },
    // [Dungeons.DragonMaze]: {
    //     "name": "Dragon Maze",
    //     "stairDirectionUp": false,
    //     "recruitingEnabled": false,
    //     "maxItemsAllowed": 20,
    //     "maxPartyMembers": 3,
    //     "keepMoney": true,
    // },
    // [Dungeons.DarkMaze]: {
    //     "name": "Dark Maze",
    //     "stairDirectionUp": false,
    //     "recruitingEnabled": false,
    //     "maxItemsAllowed": 20,
    //     "maxPartyMembers": 3,
    //     "keepMoney": true,
    // },
    // [Dungeons.SteelMaze]: {
    //     "name": "Steel Maze",
    //     "stairDirectionUp": false,
    //     "recruitingEnabled": false,
    //     "maxItemsAllowed": 20,
    //     "maxPartyMembers": 3,
    //     "keepMoney": true,
    // },
    // [Dungeons.TeamShifty]: {
    //     "name": "Team Shifty",
    //     "stairDirectionUp": false,
    //     "recruitingEnabled": false,
    //     "maxItemsAllowed": 20,
    //     "maxPartyMembers": 3,
    //     "keepMoney": true,
    // },
    // [Dungeons.TeamConstrictor]: {
    //     "name": "Team Constrictor",
    //     "stairDirectionUp": false,
    //     "recruitingEnabled": false,
    //     "maxItemsAllowed": 20,
    //     "maxPartyMembers": 3,
    //     "keepMoney": true,
    // },
    // [Dungeons.TeamHydro]: {
    //     "name": "Team Hydro",
    //     "stairDirectionUp": false,
    //     "recruitingEnabled": false,
    //     "maxItemsAllowed": 20,
    //     "maxPartyMembers": 3,
    //     "keepMoney": true,
    // },
    // [Dungeons.TeamRumblerock]: {
    //     "name": "Team Rumblerock",
    //     "stairDirectionUp": false,
    //     "recruitingEnabled": false,
    //     "maxItemsAllowed": 20,
    //     "maxPartyMembers": 3,
    //     "keepMoney": true,
    // },
    // [Dungeons.RescueTeam2]: {
    //     "name": "Rescue Team 2",
    //     "stairDirectionUp": false,
    //     "recruitingEnabled": false,
    //     "maxItemsAllowed": 20,
    //     "maxPartyMembers": 3,
    //     "keepMoney": true,
    // },
    // [Dungeons.RescueTeamMaze]: {
    //     "name": "Rescue Team Maze",
    //     "stairDirectionUp": false,
    //     "recruitingEnabled": false,
    //     "maxItemsAllowed": 20,
    //     "maxPartyMembers": 3,
    //     "keepMoney": true,
    // },
});